POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "richard",
    "number": "221-458-8974"
}

###
# Error
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Arto Hellas",
    "number": "040-123456"
}